apiVersion: v1
kind: Pod
metadata:
  name: kubepod3
spec:
  containers:
  - name: itea-lab3
    image: mcnac/lab3
    ports:
     - containerPort: 80
    resources:
    livenessProbe:
           initialDelaySeconds: 60
           periodSeconds: 5
           httpGet:
            path: /
            port: 80
    
    
         