apiVersion: v1
kind: Pod
metadata:
  name: kubepod4
spec:
  containers:
  - name: itea-lab3
    image: mcnac/lab3
    ports:
     - containerPort: 80
    resources:
    livenessProbe:
           initialDelaySeconds: 60
           periodSeconds: 5
           httpGet:
            path: /
            port: 80
    readinessProbe:
      httpGet:
        path: / 
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    
         