apiVersion: v1
kind: Pod
metadata:
  name: kubepod5
spec:
  containers:
  - name: itea-lab2
    image: mcnac/lab2
    ports:
     - containerPort: 80
    resources:
    livenessProbe:
           initialDelaySeconds: 60
           periodSeconds: 5
           httpGet:
            path: /health 
            port: 80
    readinessProbe:
      httpGet:
        path: /health 
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10

  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
   
  

    