apiVersion: v1
kind: Pod
metadata:
  name: kubepodwithlabel
  labels:
    env: development
spec:
  containers:
  - name: itea
    image: mcnac/lab2
    ports:
    - containerPort: 5000
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"