apiVersion: v1
kind: ReplicationController
metadata:
  name: rcsise
spec:
  replicas: 1
  selector:
    app: net.core
  template:
    metadata:
      name: itead-devops
      labels:
        app: itea
    spec:
      containers:
      - name: itea
        image: mcnac/lab2
        ports:
        - containerPort: 5000